# Generated by Django 3.0.7 on 2020-06-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victim', models.CharField(max_length=64)),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Murderer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('murder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='murderers', to='accountability.Murder')),
            ],
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('murder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequences', to='accountability.Murder')),
            ],
        ),
    ]
