# Generated by Django 3.0.7 on 2020-06-06 16:28

from django.db import migrations

def initialize(apps, schema_editor):
    Murder = apps.get_model('accountability', 'Murder')
    Murderer = apps.get_model('accountability', 'Murderer')
    Consequence = apps.get_model('accountability', 'Consequence')

    george_floyd = Murder(
        victim='George Floyd',
        video='https://www.youtube.com/watch?v=vksEJR9EPQ8',
    )
    george_floyd.save()

    derek_chauvin = Murderer(murder=george_floyd, name='Derek Chauvin')
    derek_chauvin.save()
    tou_thau = Murderer(murder=george_floyd, name='Tou Thao')
    tou_thau.save()
    j_alexander_kueng = Murderer(murder=george_floyd, name='J. Alexander Kueng')
    j_alexander_kueng.save()
    thomas_lane = Murderer(murder=george_floyd, name='Thomas Lane')
    thomas_lane.save()

    Consequence(murder=george_floyd, text='Derek Chauvin has been charged with second-degree murder.').save()
    Consequence(murder=george_floyd, text='The other officers have been charged with aiding and abetting second-degree murder').save()

    eric_garner = Murder(
        victim='Eric Garner',
        video='https://www.youtube.com/watch?v=N__5p_dNW3U',
    )
    eric_garner.save()

    daniel_pantaleo = Murderer(murder=eric_garner, name='Daniel Pantaleo')
    daniel_pantaleo.save()
    justin_damico = Murderer(murder=eric_garner, name='Justin Damico')
    justin_damico.save()

    Consequence(murder=eric_garner, text='A grand jury declined to indict Daniel Pantaleo').save()
    Consequence(murder=eric_garner, text='The US DOJ also declined to file any charges').save()
    Consequence(murder=eric_garner, text='No charges were filed against Justin Damico').save()

    daniel_shaver = Murder(
        victim='Daniel Shaver',
        video='https://www.youtube.com/watch?v=VBUUx0jUKxc',
    )
    daniel_shaver.save()

    philip_brailsford = Murderer(murder=daniel_shaver, name='Philip Brailsford')
    philip_brailsford.save()
    charles_langley = Murderer(murder=daniel_shaver, name='Charles Langley')
    charles_langley.save()

    Consequence(murder=daniel_shaver, text='Brailsford was charged with second degree murder, but acquitted.').save()
    Consequence(murder=daniel_shaver, text='Brailsford was reinstated by Mesa Police Department.').save()
    Consequence(murder=daniel_shaver, text='Brailsford retired on medical grounds citing PTSD from the shooting, to a pension of $2500/mo.').save()
    Consequence(murder=daniel_shaver, text='No charges were filed against Langley.').save()

class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize, reverse_code=None),
    ]
